# This workflow will add syhunt dast reports to the build process.
# For more information, see https://www.syhunt.com/pt/?n=Docs.SyhuntIntegrationGitHub

name: syhunt DAST test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v4
      - run: ScanConf.exe https://github.com/Gebarito/AgendaAi-APP.git
      - name: 'Syhunt Report'
        uses: actions/upload-artifact@v4
        if: failure()
        with:
         name: syhunt-report
         path: report.pdf
         if-no-files-found: error
