# This workflow will add syhunt reports to the build process.
# The workflow will report any medium or higher risk issues found by Syhunt Code.
# then will upload the PDF report file to the artifacts section of the build.
# For more information, see https://www.syhunt.com/pt/?n=Docs.SyhuntIntegrationGitHub

name: Syhunt test
on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v3
      - run: Start-CodeScan -pfcond 'fail-if:risk=mediumup' -output 'report.pdf'
      - name: 'Syhunt Report'
        uses: actions/upload-artifact@v3
        if: failure()
        with:
         name: syhunt-report
         path: report.pdf
         if-no-files-found: error
